footprint: [[0.27, 0.0], [-0.15, 0.26], [-0.15, -0.26]]
inflation_radius: 0.2
max_obstacle_height: 1.3
robot_radius: 0.27

transform_tolerance: 0.50
robot_base_frame: base_link
update_frequency: 5.0
publish_frequency: 2.0

resolution: 0.05
