global_frame: map
rolling_window: false

plugins: 
    - {name: static,                  type: "costmap_2d::StaticLayer"}
    - {name: obstacles,               type: "costmap_2d::ObstacleLayer"}
    - {name: inflation,               type: "costmap_2d::InflationLayer"}

static:
    map_topic: /map
    subscribe_to_updates: true


obstacles:
    observation_sources: laser
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: scan, inf_is_valid: true}

inflation:
    inflation_radius: 0.20