acc_lim_th: 3.2
acc_lim_x: 2.5
acc_lim_y: 2.5
max_trans_vel: 0.55
min_trans_vel: 0.0

max_vel_x: 0.2
min_vel_x: 0.0
max_vel_y: 0.1
min_vel_y: -0.1
max_rot_vel: 0.5
min_rot_vel: 0.15

yaw_goal_tolerance: 0.3
xy_goal_tolerance: 0.2